application:
  deploy:
    environment: "default"

# Swagger
springdoc:
  api-docs:
    path: "/api/docs/schema"
  swagger-ui:
    path: "/api/docs/swagger-ui"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_MYSQL_HOST}/${DATABASE_MYSQL_SCHEMA:bellsafehouse}?${DATABASE_MYSQL_OPTION:charset=utf8mb4,utf8&createDatabaseIfNotExist=true}
    username: ${DATABASE_MYSQL_USER}
    password: ${DATABASE_MYSQL_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      platform: mysql
      encoding: utf-8
  test:
    database:
      replace: none
  liquibase:
    change-log: classpath:/db/changelog-master.yaml
    database-change-log-table: database_changelog
    database-change-log-lock-table: database_changelog_lock

security:
  jwt:
    signature-key: ${SECURITY_JWT_SIGNATURE_KEY}
    refresh:
      expiration-minute: ${SECURITY_JWT_REFRESH_EXPIRATION_MINUTE:43200}
      auto-renew-minute: ${SECURITY_JWT_REFRESH_AUTO_RENEW_MINUTE:10080}
    access:
      expiration-minute: ${SECURITY_JWT_ACCESS_EXPIRATION_MINUTE:720}

logging:
  level:
    liquibase: INFO
    org:
      springframework:
        transaction:
          interceptor: TRACE
