application:
  deploy:
    environment: "default"

# Swagger
springdoc:
  api-docs:
    path: "/docs/schema"
  swagger-ui:
    path: "/docs/swagger-ui"

server:
  servlet:
    context-path: "/api"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_MYSQL_HOST}/${DATABASE_MYSQL_SCHEMA:bellsafehouse}?${DATABASE_MYSQL_OPTION:charset=utf8mb4,utf8&createDatabaseIfNotExist=true}
    username: ${DATABASE_MYSQL_USER}
    password: ${DATABASE_MYSQL_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_batch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      platform: mysql
      encoding: utf-8
  test:
    database:
      replace: none
  liquibase:
    change-log: classpath:/db/changelog-master.yaml
    database-change-log-table: database_changelog
    database-change-log-lock-table: database_changelog_lock
  mail:
    default-encoding: UTF-8
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:25}
    username: ${SMTP_USERNAME:user}
    password: ${SMTP_PASSWORD:test}
    properties:
      mail:
        smtp:
          timeout: 5000
          auth: true
          starttls:
            enable: ${SMTP_AUTH_TLS:false}
  thymeleaf:
    prefix: classpath:/mail-templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

security:
  jwt:
    signature-key: ${SECURITY_JWT_SIGNATURE_KEY}
    refresh:
      expiration-minute: ${SECURITY_JWT_REFRESH_EXPIRATION_MINUTE:43200}
      auto-renew-minute: ${SECURITY_JWT_REFRESH_AUTO_RENEW_MINUTE:10080}
    access:
      expiration-minute: ${SECURITY_JWT_ACCESS_EXPIRATION_MINUTE:720}

i18n:
  basename: classpath:/lang/messages
  encoding: UTF-8
  cacheSeconds: 180

frontend_url:
  reset: "https://bellsafehouse.com/resetPassword?resetToken="

logging:
  level:
    liquibase: INFO
    org:
      springframework:
        transaction:
          interceptor: TRACE
