apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_API_SERVICE_NAME}
  namespace: ${APPLICATION_NAMESPACE}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: ${APPLICATION_API_SERVICE_NAME}
  selector:
    app: ${APPLICATION_NAME}
    env: ${APPLICATION_ENVIRONMENT}
    type: api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_DEPLOYMENT_NAME}
  namespace: ${APPLICATION_NAMESPACE}
  annotations:
    kubernetes.io/change-cause: "${APPLICATION_CHANGE_CAUSE}"
    bellsoft.net/application: ${APPLICATION_NAME}
    bellsoft.net/environment: ${APPLICATION_ENVIRONMENT}
  labels:
    app: ${APPLICATION_NAME}
    env: ${APPLICATION_ENVIRONMENT}
    type: api
spec:
  replicas: ${APPLICATION_REPLICAS}
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
      env: ${APPLICATION_ENVIRONMENT}
      type: api
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
        env: ${APPLICATION_ENVIRONMENT}
        type: api
      annotations:
        bellsoft.net/application: ${APPLICATION_NAME}
        bellsoft.net/environment: ${APPLICATION_ENVIRONMENT}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${APPLICATION_IMAGE_URL}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: DEPLOY_ENVIRONMENT
              value: "${DEPLOY_ENVIRONMENT}"
          ports:
            - containerPort: 8080
